[workspace]
resolver = "2"
members = ["crates/eunoia", "crates/eunoia-wasm"]
default-members = ["crates/eunoia"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Johan Larsson"]
license = "MIT"
repository = "https://github.com/jolars/eunoia"
